# IMPORT

# FUNCTION
def elem_counter(sequence, Alphabet):
    dict_count = {}
    for nucleotide in Alphabet:
        dict_count[nucleotide] = 0
    for elem in sequence:
        dict_count[elem] += 1
        
    list_count = []
    for _,value in dict_count.items():
        list_count.append(value)
    print(f"{list_count[0]} {list_count[1]} {list_count[2]} {list_count[3]}"  )

# PARAMETER
sequence = "GGAGTTCGCGACTCGATTACTAAGAAATGAAGGGATGAACGCCTCGGTAGTTGGGAGACCCAGGCGCGGCTGCCCCTTCGATTACGACCCACCCGAACATTACAGCGGCGGGTGCCATGTCCTTCCGTAAAGCCTAGAAATTTTCCCCATCCCATCTCATATTGGAGTTCCGCTCATTCGCCTATTGATCCGTAGATAATCGCCATCCGGGACAGGGTTTGATTCTCTGTCTTTAGAGGTGGTGAGCAGCGCAAATGGTACCATCTTTCCGGAGCGGGTTCGCATAAAGCTCGACAGTCGGTTACCGCCAGCTGATCCTGCAGTTAATACCAGGAGCAAGCACTTATACCTCGAGCTTGGTAAGAGTTCTGCATACTATGTCGCCTCCAGGATGCTTACGAGTGTAGTTTCGGAGGAGACTCAAATCTTTGGTGAGGGAAGGAACTAACATTACGTCTAGACCCTTTGCGCAACCTGAAATAGGAAGATCGTGGGGAGCAAAGGCTTGCTAAGGTCCTTTGCATGACAAACCCCTATCGGCGCTCATAACACCTACGACTGAAAGCTCCCTTACCTACTCGTATCCTACAAGAAGATAATTCTTAGAACGTTAACCTCTTAGCGGGCACTCTTGCTGCAATGAGACAGATCTAAAACGCAGAGCGACGGACTAGAACATTATCGGAACACGCATGTATACTTCGTGCGTGCGACATGCTTCGCGCTAGCTGCAGTTTCTGTACCAAGTTCGCTACTGAAGGCAGTTTCTATTAATAGTTCCGACTGTGAACTACCTCGTTCGTTCGTTGGCGACCTCAGGCATACCAGTCGGTGTGGAAGCAAGACGGATCTATTGTAGGACACAGAAAGATACACGTGAGCAAATAAACCGCGAAACGCGTCCAGTGACGGTAAGACCGTACGAATCCGTGGGATTGTCTAAGTCTCGGGTACCAACAGCCCAGAATAGGTGATTAAATACCACGGCAAAA"
Alphabet = ["A", "C", "G", "T"]

# PROGRAM
elem_counter(sequence, Alphabet)