# IMPORT

# FUNCTION
def reverse_complementary(dna_string, dict_complementary):
    dna_list = list(dna_string)
    dna_list.reverse()
    dna_list_reverse = dna_list
    dna_list_reverse_complementary = []
    for elem in dna_list_reverse:
        dna_list_reverse_complementary.append(dict_complementary[elem])
    print("".join(dna_list_reverse_complementary))


# PARAMETER
dict_complementary = {"A": "T",
                      "T": "A",
                      "C": "G",
                      "G": "C"}
dna_string = "CCTGGCGGTGTTGACAGTAGGTGTGGAAGATAGGCGCTGGGTACAAGTATGGCACACACATATAATCCTCTGGAATGATCCGTGGAACCTATGCGTGTGACATGGTTGTCGCTCCCAGTGCAACTTTTAGATTTAATGACGACGGAGGGCTTAGTCGTGTCGTAATTGGAGGCTTATTAGAATGAATCTTCCAAAGAAGAGGCGTATGCTTGAGGATCTCGGGTAGATTATGTCAGTACTCAGGACTCCTCTGACCTGCACATCAGTGGGGATACAGGGCCACATGACATGTCGCCTCCAGCCATCCATGCACGCTTTCTTCCCTGTACAAAGAGCTCGCTCGTCAGACTCCTGACTCAGTGAAACTGGCAAGCGCGAAATACGGGCAGTAGTGTGCCTACCCCTTGATGTCTATCAGTTTGGACTTGCGTCAGGAACTCGAACGACTTCCCATCCGTGCCGGTAACAAGAAAACACGTGGTATCTACCACTCAATATTCAGTGGAAAGGACCAAATCGCTCACTATAAGTCTCAACGCCTCTCCAATTAGAAGACGGGATTCCAGTTACCGGTTATTCTTGGACTAACTCAGCTCACCAGGGCACTGACCCCACGAATCCGCAGGCTCCGATTTCTCGTCCATTAGGAACAATCCATGCCGACATTATTTAGTTTACCAGAGGGGTACTCGAGAAGCGCCGCCGCATCTAAGTTAAATACCAGTAGTTGACATCACTAAGCAGAGCGCGCTACACCTCGTGGGAGCTCAACCTTCGGATCGGGCAGCGCGCGGTACTTAATCTGTGTCGGGTCGACAGCGGTTTCCAAATTAGCTCACCGCCGCTTACGCTACTGGGGATACGTGTGTTCCATAGGGTGCACCCCATAAAGATATACATGGCTCTAGATCACACTTGGGG"

# PROGRAM
reverse_complementary(dna_string, dict_complementary)