# IMPORT

# FUNCTION
def motif_position(seq, motif):
    list_seq = list(seq)
    len_list_seq = len(list_seq)
    list_motif = list(motif)
    len_list_motif = len(list_motif)

    list_position = []
    for index, _ in enumerate(list_seq):
        if index + len_list_motif < len_list_seq:
            if motif == seq[index: index + len_list_motif]:
                list_position.append(index+1)
    for i in range(len(list_position)):
        print(list_position[i], end = ' ')



# PARAMETER
seq = "TGGTAGGACCAGGGGACCAGAGGACCAGGCATAAAGGGGACCAGGGACCAGTGGACCAGTGGAATGTAGGAAGGACCAGGGGGGGACCAGTGGGACCAGTCGGACCAGGAGGACCAGGGACCAGGGACCAGTAACCGGACCAGGGACCAGGGACCAGTGGACCAGTGGTAGGACCAGGGACCAGGGACCAGAGTGGACCAGTGTGGGACCAGTGTGTCCAGTACGAGGGACCAGAGTGCTGGACCAGGGGACCAGGGATTCATGGACCAGGGACCAGGCCGGACCAGTGCGGACCAGGATGGGGACCAGGACGGACCAGAGGACCAGGGGACCAGTTTGGGACCAGAGTCGGACCAGGGACCAGGGGGACCAGGGACCAGCTCTCACGGATCTCCGGACCAGGGACCAGTAAGCCTGGACCAGGGACCAGGAACGGACCAGCAGGACCAGGGACCAGGAGGACCAGCGGACCAGGGACCAGGGACCAGGATGTCAAGGACCAGGGACCAGAAAGGACCAGCTCGGACCAGCAGGACCAGTACGGACCAGTGGACCAGAGGACCAGTGGACCAGACTGAGGACCAGGGACCAGGGACCAGGTGAACTACAGGAACTGGGGGACCAGGGACCAGTAGGACCAGAGGACCAGGGACCAGGGGACCAGTAACACGGACCAGATAAATGGACCAGTGGACCAGGGACCAGGTGACTGGACCAGGGGACCAGCATTGGACCAGTTCAGGACCAGATTCGGACCAGGGAATATGGACCAGACGGACCAGCTGACTTGCAAACCCCGTCGGACCAGGGGACCAGTGGACCAGCACGCTGGACCAGGGACCAGCCCTCGGGGCAGGACCAGAGGACCAGAAGGACCAGGGGACCAGGGACCAGTGGACCAGTAAACGGACCAGTGGACCAGGTACTTGGACCAGGGACCAG"
motif = "GGACCAGGG"

# PROGRAM
motif_position(seq, motif)
